Allows installation of Juno and Atom older versions (#15511)
Users who are on older versions of Atom are encountering following error (Source:- https://discourse.julialang.org/t/error-when-starting-juliapro-v1-4-1/40223)
```
ERROR: LoadError: LoadError: ArgumentError: Package Atom does not have Traceur in its dependencies:
- If you have Atom checked out for development and have
  added Traceur as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Atom
Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:905
 [2] include(::Module, ::String) at .\Base.jl:377
 [3] include(::String) at C:\Users\...\.juliapro\JuliaPro_v1.4.1-1\packages\Atom\wlPiw\src\Atom.jl:4
 [4] top-level scope at C:\Users\...\.juliapro\JuliaPro_v1.4.1-1\packages\Atom\wlPiw\src\Atom.jl:67
 [5] include(::Module, ::String) at .\Base.jl:377
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:331 [inlined]
 [8] eval(::Expr) at .\client.jl:449
 [9] top-level scope at .\none:3
in expression starting at C:\Users\...\.juliapro\JuliaPro_v1.4.1-1\packages\Atom\wlPiw\src\profiler\traceur.jl:1
in expression starting at C:\Users\...\.juliapro\JuliaPro_v1.4.1-1\packages\Atom\wlPiw\src\Atom.jl:67
ERROR: LoadError: Failed to precompile Atom [c52e3926-4ff0-5f6e-af25-54175e0327b1] to C:\Users\...\.juliapro\JuliaPro_v1.4.1-1\compiled\v1.4\Atom\w9XOh_5ybJQ.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] top-level scope at C:\Users\...\AppData\Local\JuliaPro-1.4.1-1\.atom\packages\julia-client\script\boot_repl.jl:56
 [7] include(::Module, ::String) at .\Base.jl:377
 [8] exec_options(::Base.JLOptions) at .\client.jl:288
 [9] _start() at .\client.jl:484
in expression starting at C:\Users\...\AppData\Local\JuliaPro-1.4.1-1\.atom\packages\julia-client\script\boot_repl.jl:1

```

This fixes above issue