libblastrampoline_jll: Reflect backporting in Julia v1.9 versions (#150216)
LBT_jll v5.7.0 was backported to Julia v1.9.0 in [JuliaLang/julia#49302][jl-49302]
and LBT_jll v5.8.0 was backported to Julia v1.9.1 in [JuliaLang/julia#49680][jl-49680],
so these versions should be reflected in the registry.

Doing so fixes an observable problem when using [Resolver.jl][Resolver.jl] to
test the minimum-supported versions of a package. Take for instance the
minimal sample Project.toml:

```bash
$ cat /tmp/mwe/Project.toml
[deps]
libblastrampoline_jll = "8e850b90-86db-534c-a0d3-1478176c7d93"
```

Trying to resolve the package environment for Julia v1.9 fails:

```bash
$ julia ./resolve.jl --julia=1.9 --min=@deps /tmp/mwe
ERROR: LoadError: Unsatisfiable:
	1222c4b2-2114-5bfd-aeef-88e4692bbb3e julia => 1.9.0
	8e850b90-86db-534c-a0d3-1478176c7d93 libblastrampoline_jll => nothing

Stacktrace:
...
```
(where the additional logging is a proposed feature in
[StefanKarpinski/Resolver.jl#22][res-22])

With this change to the registry, resolving the package environment
succeeds.

[jl-49302]: https://github.com/JuliaLang/julia/pull/49302/changes#diff-368ce867d88c59e2b536cb53963a693493c8de40ea2a3f88bd19ace9505dea1d
[jl-49680]: https://github.com/JuliaLang/julia/pull/49680/changes#diff-368ce867d88c59e2b536cb53963a693493c8de40ea2a3f88bd19ace9505dea1d
[Resolver.jl]: https://github.com/StefanKarpinski/Resolver.jl
[res-22]: https://github.com/StefanKarpinski/Resolver.jl/pull/22